### ISSUE TITLE
Need a new version on NPM

### ISSUE THREAD

**Issue by EmmaSimon** [rt2zz/redux-action-buffer#18]
There's no way to use redux-persist v5 with this unless you point to a git repo.

**Comment by craigcoles** [comment]
@rt2zz Is it possible to make this happen?

**Comment by rt2zz** [comment]
just published v1.2.0

I suppose we need to update the readme as well, what is the new config that allows it to work with persist v5?

**Comment by EmmaSimon** [comment]
All the breaker/passthrough stuff. It's already in the README on here.
