### ISSUE TITLE
import { REHYDRATE } from 'redux-persist/lib/constants'; not 'redux-persist/constants'

### ISSUE THREAD

**Issue by luojxxx** [rt2zz/redux-action-buffer#19]
Changing that fixed the problem that I had with the example code. (Basically it was saying it couldn't find that module)

**Comment by cmelgarejo** [comment]
I had this same issue with my app, and gave a really cryptic error on a transform module, granted I didn't followed the updates on this `redux-persist` but when there are namespace changes would be nice to have a warning thrown at you instead of an babel transform error

**Comment by rt2zz** [comment]
thanks, resolved: https://github.com/rt2zz/redux-action-buffer/commit/6759c57bd4a69c536aab42ab83123f261dbb55b6
