### ISSUE TITLE
Trying to use redux-action-buffer with redux-persist

### ISSUE THREAD

**Issue by runn1ng** [rt2zz/redux-action-buffer#9]
I am trying to use redux-persist with redux-action-buffer, but it doesn't seem to be working as described in the documentation.

My simple example is as follows:

````es6
import {applyMiddleware, createStore, compose} from 'redux';
import {persistStore, autoRehydrate} from 'redux-persist';
import createActionBuffer from 'redux-action-buffer';
import {REHYDRATE} from 'redux-persist/constants';

function reducer(state = {foo: ["bar"]}, action) {
  if (action.type === 'ADD_FOO') {
    return {
      foo: [...state.foo, action.item]
    }
  }
  return state;
}

const enhancer = compose(
  autoRehydrate(),
  applyMiddleware(
    createActionBuffer(REHYDRATE)
  )
);

const store = createStore(
  reducer,
  undefined,
  enhancer
);

persistStore(store);

store.dispatch({
  type: 'ADD_FOO',
  item: 'baz'
});

store.dispatch({
  type: 'ADD_FOO',
  item: 'hocus pocus'
});

setTimeout(() => {
  // the state is correct...
  console.log(store.getState());
  // but nothing in the localStorage!
  console.log(localStorage);
}, 1000);
````

According to [redux-persist documentation](https://github.com/rt2zz/redux-persist#about-auto-rehydrate) and [redux-action-buffer documentation](https://github.com/rt2zz/redux-action-buffer#redux-persist-example), this should work. Yet it doesn't and nothing is saved to localstorage.

If I change the store.dispatch code to run inside the callback, as in

    persistStore(store, undefinded, () => {
        store.dispatch(....

it seems to be working; but in that case, the `redux-action-buffer` is not doing what it should and it doesn't actually buffer anything.

I am beginning with Redux so I might be missing something. :)

**Comment by rt2zz** [comment]
that is curious, code looks correct. The only thing I can think of that is "atypical" is not using `combineReducers`. Still I would expect this to work.

I will try to give your code a run at some point in the future. In the meantime I might suggest adding `combineReducers` and see if that helps, or debugging persistStore to see what happens when it receives the state subscription.

**Comment by runn1ng** [comment]
I copy-pasted the code from online examples. :)

I will try the combineReducers then

On May 16, 2017 12:46 AM, "Zack Story" <notifications@github.com> wrote:

that is curious, code looks correct. The only thing I can think of that is
"atypical" is not using combineReducers. Still I would expect this to work.

I will try to give your code a run at some point in the future. In the
meantime I might suggest adding combineReducers and see if that helps, or
debugging persistStore to see what happens when it receives the state
subscription.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rt2zz/redux-action-buffer/issues/9#issuecomment-301626471>,
or mute the thread

**Comment by runn1ng** [comment]
combineReducers doesn't help, it still doesn't work.

I will look at persistStore
